### ISSUE TITLE
Application does not open

### ISSUE THREAD

**Issue by robertsanseries** [davidmhewitt/torrential#49] opened 2017-08-17 22:31 UTC
Console:

```
robertsanseries@robert-notebook:~$ com.github.davidmhewitt.torrential 
com.github.davidmhewitt.torrential: symbol lookup error: com.github.davidmhewitt.torrential: undefined symbol: granite_app
```

**Comment by davidmhewitt** [comment] 2017-08-18 12:56
Hi Robert,

Thanks for reporting this. This is a duplicate of #35. It suggests that you're using a newer version of Granite than what Torrential supports.

Do you have the elementary daily PPA installed or have you installed a newer version of Granite manually?

I'm still looking into ways to make Torrential work with both versions of Granite, but for the moment, the only way to solve this is to go back to the stable version of Granite.

**Closed** 2017-08-24 17:25 UTC

**Comment by robertsanseries** [comment] 2017-08-24 17:32
@davidmhewitt Sorry, the notifications in my github are not working correctly.

I only use elementary-sdk.

I'll test later with an earlier version. (I have a test environment installed) :D
