### ISSUE TITLE
Doesn't open uPnP ports

### ISSUE THREAD

**Issue by dmanlfc** [davidmhewitt/torrential#71] opened 2017-10-26 01:22 UTC
I have checked my Router - Torrential is not requesting the uPnP ports be opened for BitTorrent to work on my router. Therefore I don't get metadata etc to download.

Other Torrent clients like Deluge work just fine.

**Comment by ar0ra1** [comment] 2017-10-30 07:19
Exactly,
Because of this the speed is very low.
I was downloaded a torrent and it was giving only 100kbps of speed
I added the same torrent to qBittorrent and
Viola! 4.2mbps steady download.
(and for checking purposes i did allow un-encrypted peers)

**Comment by davidmhewitt** [comment] 2017-12-06 16:45
Hello,

Thank you for reporting this.

If possible, could you test to see if the same issue occurs with Transmission? As Torrential is based on Transmission, it would be good to identify whether the problem exists with Torrential or Transmission.

This is not something I am able to reproduce as Torrential correctly opens uPnP ports with my router.

**Comment by ar0ra1** [comment] 2018-01-03 05:34
Torrential issue.
I have torrential, transmission and qBittorrent running simultaneously. 

![torrent](https://user-images.githubusercontent.com/20777462/34509923-a320b7c6-f075-11e7-849c-30aa237f3298.png)

**Comment by davidmhewitt** [comment] 2018-02-18 20:55
Hello,

Is anyone able to re-test this?

I've updated libtransmission, which may resolve this issue.

**Comment by davidmhewitt** [comment] 2018-03-05 14:37
Closing as I have not had any further information about this issue and I am unable to reproduce this with my setup. uPnP ports are opened correctly on my router.

**Closed by davidmhewitt** 2018-03-05 14:37 UTC
Labels: Needs Information

**Comment by davidmhewitt** [comment] 2018-03-05 14:57
Thanks!

As Torrential uses libtransmission, it may still appear as "Transmission" in your router's uPnP table that you have shown a screenshot of above. So that may be something to watch out for.

It is also possible that it uses the same port by default, so if Transmission was running at the same time, it may not have been able to open the port because of a conflict.

**Comment by ar0ra1** [comment] 2018-03-05 17:12
@davidmhewitt 
I'll take all the test cases and report soon!

**Comment by ar0ra1** [comment] 2018-04-03 09:48
@davidmhewitt 
I checked my router's UPnP and it doesn't show it!

I only had Torrential installed and it wasn't showing up.
I launched qBittorrent and came up immediately. 

I can confirm it's a torrential issue.

Latest Torrential version, just downloaded from the AppCenter.
