### ISSUE TITLE
Don´t Open

### ISSUE THREAD

**Issue by alainhuntt** [davidmhewitt/torrential#58] opened 2017-09-24 12:07 UTC
com.github.davidmhewitt.torrential: symbol lookup error: com.github.davidmhewitt.torrential: undefined symbol: granite_app

**Comment by davidmhewitt** [comment] 2017-09-25 10:10
Duplicate of #49 

Torrential is not currently compatible with the newest version of Granite. I assume you are either using the elementary daily PPA or have installed a newer version of Granite than what is normally available on a standard elementary OS installation.

I have a workaround for this issue that will be in the next release of Torrential, but for now, you'll have to go back to the stable, supported version of Granite if you wish to use Torrential.

**Closed by davidmhewitt** 2017-09-25 10:10 UTC
