### ISSUE TITLE
Torrential opens wrong folder when using 'Show in file browser'

### ISSUE THREAD

**Issue by konek3** [davidmhewitt/torrential#105] opened 2018-09-24 15:54 UTC
It seems that app doesn't parse special signs correctly when using **Show in file browser** option. Some of my torrents have [] brackets in name, when I'm trying to use this feature it tries to open folder named like the first file in the torrent, which obviously does not exists since it's not a folder but a file.

**Comment by peteruithoven** [comment] 2018-10-12 14:43
I think this is a duplicate of: https://github.com/davidmhewitt/torrential/issues/12 and https://github.com/davidmhewitt/torrential/issues/43
This is fixed in Juno.

**Closed** 2018-10-25 11:01 UTC
