### ISSUE TITLE
[2023-04-10 05:58:40.407] tr_crypto_utils: OpenSSL error: error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by sfxworks** [davidmhewitt/torrential#195] opened 2023-04-10 10:00 UTC
Adding a torrent to torrential and starting it crashes. This is my first use of torrential that I download using pacman

```
[2023-04-10 05:58:24.756] Transmission 3.00 (bb6b5a062e) started
[2023-04-10 05:58:24.756] RPC Server: Adding address to whitelist: 127.0.0.1
[2023-04-10 05:58:24.756] RPC Server: Adding address to whitelist: ::1
[2023-04-10 05:58:24.756] UDP: Failed to set receive buffer: requested 4194304, got 425984
[2023-04-10 05:58:24.756] UDP: Please add the line "net.core.rmem_max = 4194304" to /etc/sysctl.conf
[2023-04-10 05:58:24.756] UDP: Failed to set send buffer: requested 1048576, got 425984
[2023-04-10 05:58:24.756] UDP: Please add the line "net.core.wmem_max = 1048576" to /etc/sysctl.conf
[2023-04-10 05:58:24.756] UDP: Failed to set receive buffer: requested 4194304, got 425984
[2023-04-10 05:58:24.756] UDP: Please add the line "net.core.rmem_max = 4194304" to /etc/sysctl.conf
[2023-04-10 05:58:24.756] UDP: Failed to set send buffer: requested 1048576, got 425984
[2023-04-10 05:58:24.756] UDP: Please add the line "net.core.wmem_max = 1048576" to /etc/sysctl.conf
[2023-04-10 05:58:24.756] DHT: Reusing old id
[2023-04-10 05:58:24.756] DHT: Bootstrapping from 64 IPv4 nodes
[2023-04-10 05:58:24.756] DHT: Bootstrapping from 14 IPv6 nodes
[2023-04-10 05:58:24.806] Loaded 1 torrents
[2023-04-10 05:58:25.089] Port Forwarding (NAT-PMP): initnatpmp succeeded (0)
[2023-04-10 05:58:25.089] Port Forwarding (NAT-PMP): sendpublicaddressrequest succeeded (2)
connect: Connection timed out
[2023-04-10 05:58:39.354] Port Forwarding: State changed from "Not forwarded" to "Starting"
[2023-04-10 05:58:39.354] web: will verify tracker certs using envvar CURL_CA_BUNDLE: none
[2023-04-10 05:58:39.354] web: NB: this only works if you built against libcurl with openssl or gnutls, NOT nss
[2023-04-10 05:58:39.354] web: NB: invalid certs will show up as 'Could not connect to tracker' like many other errors
[2023-04-10 05:58:39.689] Port Forwarding: State changed from "Starting" to "???"
[2023-04-10 05:58:40.407] tr_crypto_utils: OpenSSL error: error:0308010C:digital envelope routines::unsupported
zsh: segmentation fault (core dumped)  torrential
```

**Comment by davidmhewitt** [comment] 2023-04-10 10:32
This is a duplicate of https://github.com/davidmhewitt/torrential/issues/164

I don't maintain the package in pacman, so you'll have to report this to the maintainers of the package.

**Closed by davidmhewitt** 2023-04-10 10:32 UTC

**Comment by sfxworks** [comment] 2023-04-10 11:05
Thanks. Tried searching and didn't come up with that issue #.
