### ISSUE TITLE
Show in file browser path issues

### ISSUE THREAD

**Issue by peteruithoven** [davidmhewitt/torrential#43] opened 2017-07-23 00:32 UTC
There seem to be issues with the path that's opened when clicking on "Show in file browser". For example, I've seen:
- "[" changed into a "B"
- "]" changed into a "D"
- " " changed into a "0"

I'm running 1.0.5 on Elementary OS 0.4.1 Loki.

Please let me know if can to provide more information or I can test something.

**Comment by davidmhewitt** [comment] 2017-07-24 09:02
Hi Peter,

Thank you for the bug report, this is a duplicate of #12 .

This is a bug in Pantheon Files, there is an open bug report here: https://github.com/elementary/files/issues/42

There's nothing I can do in Torrential to improve this, but I'll leave this bug report open so that other people have visibility of the issue.

**Comment by peteruithoven** [comment] 2017-10-13 01:56
Work continues at:
https://github.com/elementary/files/pull/43
https://github.com/elementary/files/pull/72

**Comment by mattcoxonline** [comment] 2018-03-27 10:23
Whenever I right click on a torrent and select "Show in File Browser" the app crashes.

![screen-recording](https://user-images.githubusercontent.com/673542/37961783-7e42deb8-31b9-11e8-8dc1-df3c97b8d2fd.gif)

**Comment by davidmhewitt** [comment] 2018-05-29 19:42
I'm going to close this as issues with opening a torrent in the file browser appear to have been resolved in Juno.

**Closed by davidmhewitt** 2018-05-29 19:42 UTC
Labels: Duplicate
