### ISSUE TITLE
Cannot change open port

### ISSUE THREAD

**Issue by jhclare** [davidmhewitt/torrential#76] opened 2017-12-13 11:16 UTC
When attempting to change the default open port, the number reverts back to the original value.

**Comment by davidmhewitt** [comment] 2018-02-19 21:14
I am unable to reproduce this issue. Can you please test again with the latest version?

If you still experience this issue, can you run Torrential from Terminal with the following command and post the output

`com.github.davidmhewitt.torrential`

Thank you

**Comment by davidmhewitt** [comment] 2018-03-05 14:38
Closing due to being unable to reproduce, please re-open this issue with more information if it still occurs for you.

**Closed by davidmhewitt** 2018-03-05 14:38 UTC
Labels: Needs Information

**Comment by riffer33** [comment] 2020-01-29 16:28
I tried this out yesterday on a new elementary os install and had the same issue.  I could enter the port forward number but it wouldn't "stick"
